final/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("recipes.urls")),
    path('admin/', admin.site.urls),
]

recipes/urls.py
from django.urls import path
from . import views

app_name = "recipes"
urlpatterns= [
    path("", views.index,name="index"),
    path("home/",views.home,name="home"),
    path("register/",views.register,name="register"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/", views.detail, name="detail"),
    path("publicar/", views.create, name="create"),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User


class Receta(models.Model):
    titulo = models.CharField(max_length = 200)
    descripcion = models.TextField()
    categoria = models.CharField(max_length = 50)
    #ENUM
    class Dificultad(models.TextChoices):
        FACIL = 'Fácil'
        MEDIA = 'Media'
        DIFICIL = 'Díficil'
        def getDificultad(self):
            return self.Dificultad(self.dificultad)
    dificultad = models.CharField(
        max_length = 8,
        choices=Dificultad.choices,
        default=Dificultad.MEDIA,
    )
    tiempo_preparacion = models.IntegerField()
    precio = models.DecimalField(max_digits=6, decimal_places=2)
    imagen_url = models.CharField(max_length= 1500)
    es_premium = models.BooleanField()

class Compra(models.Model):
    usuario_id = models.ForeignKey(User, on_delete=models.CASCADE,related_name="user")
    receta_id = models.ForeignKey(Receta,on_delete=models.CASCADE)
    monto = models.DecimalField(max_digits=6,decimal_places=2)
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    class MetodoPago(models.TextChoices):
        PAYPAL = 'Paypal'
        VISA = 'Visa'
        MASTERCARD = 'Mastercard'
        AMERICAN_EXPRESS = 'American express'
        def getMetodoPago(self):
            return self.MetodoPago(self.metodo_pago)
    metodo_pago = models.CharField(
        max_length = 20,
        choices = MetodoPago.choices,
        default = MetodoPago.VISA,
    )

# class MetodoPago(Models.Model):
    # nombre = models.CharField(max_length=25)
"""
class Pago(models.Model):
    compra_id = models.ForeignKey(Compra,on_delete=models.CASCADE)
    class MetodoPago(models.TextChoices):
        PAYPAL = 'Paypal'
        VISA = 'Visa'
        MASTERCARD = 'Mastercard'
        AMERICAN_EXPRESS = 'American express'
        def getMetodoPago(self):
            return self.MetodoPago(self.metodo_pago)
    metodo_pago = models.CharField(
        max_length = 20,
        choices = MetodoPago.choices,
        default = MetodoPago.VISA,
    )
"""

recipes/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User 
from django import forms
from django.forms import ModelForm, widgets
from django.forms.widgets import PasswordInput, TextInput
from .models import Compra, Receta

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())

class CompraForm(ModelForm):
    class Meta:
        model = Compra
        fields = ["metodo_pago"]

DIFICULTAD = [
    ('FACIL', 'Fácil'),
    ('MEDIA', 'Media'),
    ('DIFICIL', 'Díficil'),
]



class RecetaForm(ModelForm):
    class Meta:
        model = Receta
        es_premium = forms.BooleanField()
        precio = forms.DecimalField()
        dificultad = forms.ChoiceField(choices=DIFICULTAD)
        fields = ["titulo","descripcion","categoria","dificultad","tiempo_preparacion","precio","imagen_url","es_premium"]
        widgets={
            'titulo' : forms.TextInput(attrs={'class':'form-control'}),
            'descripcion' : forms.TextInput(attrs={'class':'form-control'}),
            'categoria' : forms.TextInput(attrs={'class':'form-control'}),
            'tiempo_preparacion' : forms.NumberInput(attrs={'class':'form-control'}),
            'precio' : forms.NumberInput(attrs={'class':'form-control'}),
            'imagen_url' : forms.TextInput(attrs={'class':'form-control'}),

        }

recipes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from . forms import CreateUserForm, LoginForm, CompraForm, RecetaForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, auth
from django.contrib import messages
from .models import Receta, Compra
from django.conf import settings
from cryptography.fernet import Fernet

f = Fernet(settings.ENCRYPT_KEY)

# Create your views here.
def index(request):
    form = LoginForm()
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth.login(request, user)
                messages.success(request, "Se ha ingresado correctamente")
                return HttpResponseRedirect("/home")
            else:
                messages.warning(request, "Usuario o contraseñas incorrectos")
    return render(request,"recipe/index.html",{"loginform":form})

def register(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Se ha registrado correctamente")
            return HttpResponseRedirect("") 
    return render(request,"recipe/register.html",{"registerform" : form})

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect("/")

@login_required(login_url="/")
def home(request):
    if request.method == "POST":
        precio = request.POST.get("precio")
        premium = request.POST.get("es_premium")
        todas = request.POST.get("todas")
        if precio is not None:
            recipes = Receta.objects.filter(precio = precio)
        elif premium is not None:
            recipes = Receta.objects.filter(es_premium=premium)
        else:
            recipes = Receta.objects.all()
        context = {"recipe_list" : recipes}
        return render(request, "recipe/home.html", context)
    else:
        recipes = Receta.objects.all()
        context = {"recipe_list" : recipes}
    return render(request, "recipe/home.html", context)

@login_required(login_url="/")
def detail(request,pk):
    form = CompraForm(request.POST)
    if form.is_valid():
        form.instance.usuario_id = request.user
        form.instance.receta_id = Receta.objects.get(id=pk)
        form.instance.monto = Receta.objects.get(id=pk).precio
        compra_id = pk
        form.save()
        return HttpResponseRedirect("/home")
    else:
        form = CompraForm()
    recipe = get_object_or_404(Receta, pk = pk)
    return render(request,"recipe/detail.html",{"recipe":recipe, "compraform":form})

@login_required(login_url="/")
def create(request):
    form = RecetaForm(request.POST)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/home")
    else:
        form = RecetaForm()
    return render(request,"recipe/create.html",{"recetaform":form})

recipes/templates/recipe/create.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/detail.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Crear receta</title>
</head>
<body>
    
    <div class="container">
        <div class="row p-4">
        <div class="col md-2">
            <button type="submit" class="button btn fs-4" value="0" name="precio" selected> <a class="link-underline-dark link-body-emphasis text-decoration-none" href="{% url 'recipes:home' %}">GRATIS </a></button>
        </div>
        <div class="col md-2">
            <button type="submit" class="button btn fs-4"  value="True" name="es_premium" selected><a class="link-underline-dark link-body-emphasis text-decoration-none" href="{% url 'recipes:home' %}">ES PREMIUM </a></button>
        </div>
        <div class="col md-2">
            <button type="submit" class="button btn fs-4" value="True" name="todas" selected> <a class="link-underline-dark link-body-emphasis text-decoration-none" href="{% url 'recipes:home' %}">TODAS</a></button>
        </div>
      
      <div class="col md-2">
        <button class="button btn fs-4" selected><a class="link-underline-dark link-body-emphasis text-decoration-none" href="{% url 'recipes:create' %}">PUBLICAR RECETA</a></button  {% comment %}POR ALGUNA RAZÓN SI CIERRAS EL DE BUTTON SE ROMPE EL DISEÑO DE LA PÁGINA PERO SI LO DEJAS ASÍ ABIERTO NO, NO SÉ PORQUE{% endcomment %} 
      </div>
      
        <div class="position-absolute end-0 top-0 m-5">
        <a href="{% url 'recipes:logout' %}" class="logout"><img class="logout" src="{%static 'img/logout.png' %}" alt="logout"></a>
      </div>
    </div>
</div>
<h1>Crear receta</h1>
  <form method ="POST" autocomplete = "off">
    {% csrf_token %}
    {{ recetaform.as_p }}
    <button type="submit" class="btn btn-warning">Publicar Receta</button>
  </form>
    
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</html>

recipes/templates/recipe/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/detail.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{{ recipe.titulo }}</title>
</head>
<body>
    <div class="container">
        <div class="row p-4">
          <div class="col md-2">
            <button type="submit" class="button btn fs-4" value="0" name="precio" selected> <a class="link-underline-dark link-body-emphasis text-decoration-none" href="{% url 'recipes:home' %}">GRATIS </a></button>
          </div>
          <div class="col md-2">
            <button type="submit" class="button btn fs-4"  value="True" name="es_premium" selected><a class="link-underline-dark link-body-emphasis text-decoration-none" href="{% url 'recipes:home' %}">ES PREMIUM </a></button>
          </div>
          <div class="col md-2">
            <button type="submit" class="button btn fs-4" value="True" name="todas" selected> <a class="link-underline-dark link-body-emphasis text-decoration-none" href="{% url 'recipes:home' %}">TODAS</a></button>
          </div>
          
          <div class="col md-2">
            <button class="button btn fs-4" selected><a class="link-underline-dark link-body-emphasis text-decoration-none" href="{% url 'recipes:create' %}">PUBLICAR RECETA</a></button  {% comment %}POR ALGUNA RAZÓN SI CIERRAS EL DE BUTTON SE ROMPE EL DISEÑO DE LA PÁGINA PERO SI LO DEJAS ASÍ ABIERTO NO, NO SÉ PORQUE{% endcomment %} 
          </div>
          
          <div class="position-absolute end-0 top-0 m-5">
            <a href="{% url 'recipes:logout' %}" class="logout"><img class="logout" src="{%static 'img/logout.png' %}" alt="logout"></a>
          </div>
        </div>
      </div>
    <div class="container">
        <div class="row">
            <div class="col md-3 text-center fs-4">
                <img src="{{ recipe.imagen_url }}" class="mt-3" alt="{{ recipe.titulo }}"><br>
                <h1 class="mt-3">{{ recipe.titulo }}</h1>
                <button class="btn btn-warning btn-lg mt-3">Comprar receta</button>
            </div>
            <div class="col md-3">
                <h6>{{recipe.descripcion}}</h6><br>
                <h4>Dificultad: {{ recipe.dificultad }}</h4>
                <h4>Categoria: {{ recipe.categoria }}</h4>
                <h4>Tiempo de preparación: {{ recipe.tiempo_preparacion }} minutos.</h4>
                <h4>Precio: ${{ recipe.precio }}</h4>
                <h4>{% if recipe.es_premium == True %} Se desbloqueará al comprar premium. {% else %} Es gratis. {% endif %}</h4>
            </div>
        </div>
    </div>
    <div class="container">
        <form id="pago-form" method="POST" autocomplete="off">
            <div class="mb-3">
                {{ compraform.as_p }}
                {% csrf_token %}
                <button type="submit" class="btn btn-warning">Pagar</button>
            </div>
          </form>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>

recipes/templates/recipe/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Home </title>
    <link href="{% static 'css/home.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <form method="POST">
      {% csrf_token %}
      <div class="container">
        <div class="row p-4">
          <div class="col md-2">
            <button type="submit" class="button btn fs-4" value="0" name="precio" selected> GRATIS </button>
          </div>
          <div class="col md-2">
            <button type="submit" class="button btn fs-4"  value="True" name="es_premium" selected>ES PREMIUM </button>
          </div>

          <div class="col md-2">
            <button type="submit" class="button btn fs-4" value="True" name="todas" selected>TODAS</button>
          </div>
          
          <div class="col md-2">
            <button class="button btn fs-4" selected><a class="link-underline-dark link-body-emphasis text-decoration-none" href="{% url 'recipes:create' %}">PUBLICAR RECETA</a></button  {% comment %}POR ALGUNA RAZÓN SI CIERRAS EL DE BUTTON SE ROMPE EL DISEÑO DE LA PÁGINA PERO SI LO DEJAS ASÍ ABIERTO NO, NO SÉ PORQUE 
          {% endcomment %}
          </div>
          
          <div class="position-absolute end-0 top-0 m-5">
            <a href="{% url 'recipes:logout' %}" class="logout"><img class="logout" src="{%static 'img/logout.png' %}" alt="logout"></a>
          </div>
        </div>
      </div>
      {% if recipe_list %}
      <div class="container text-center">
        <div class="row">
          {% for recipe in recipe_list %}
            <div class="col md-6">
              <a href="{% url 'recipes:detail' recipe.pk %}"><img src="{{ recipe.imagen_url }}" alt="Cupcake"><br></a>
              <a class="link-underline-dark link-body-emphasis text-decoration-none" href="{% url 'recipes:detail' recipe.pk %}">{{ recipe.titulo }}</a>
            </div>
          {% endfor %}
        </div>
      </div>
      {% else %}
        <p>No hay recetas todavia</p>
      {% endif %}
      <br>
    </form>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>

recipes/templates/recipe/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Recetas</title>
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    
    <div class="container">
      <div class="left-side">
        <img src="{% static 'img/cupcake.jpg' %}" alt="Cupcake">
      </div>
      <div class="right-side">
        <div class="text-center">
          <h1>RECETAS</h1>
        </div>
        <div class="tabs">
          <button id= "login" class="active position-relative" onclick="loginShow()" data-url="{% url 'recipes:index' %}">Iniciar Sesión</button>
          <button id ="register" class="position-relative" onclick="RegisterShow()" data-url="{% url 'recipes:register' %}">Registrarme</button>
        </div>
        <div id="loginTab">
          <form id="login-form" method="POST" autocomplete="off">
            <div class="mb-3">
              {{loginform.as_p}}
            {% csrf_token %}
            <button type="submit" class="btn btn-warning w-100">Iniciar Sesión</button>
            </div>
          </form>
          
          <div id ="registerTab" class="position-relative">
          <form id="register-form" method="POST" autocomplete="off">
            <div class="mb-3">
              {{registerform.as_p}}
              {% csrf_token %}
              <button type="submit" class="btn btn-warning w-100 position-relative">Registrarse</button>
            </div>
        </form>
      </div>
        </div>
        
    </div>
  </body>
  <script>

function hide (elements) {
  elements = elements.length ? elements : [elements];
  for (var index = 0; index < elements.length; index++) {
    elements[index].style.display = 'none';
  }
}

function show (elements, specifiedDisplay) {
  elements = elements.length ? elements : [elements];
  for (var index = 0; index < elements.length; index++) {
    elements[index].style.display = specifiedDisplay || 'block';
  }
}

function loginShow() {
  var url = document.getElementById("login").getAttribute("data-url");
  document.location.href = url
  const register = document.getElementById("register");  // Get the DIV element
  register.classList.remove("active"); // Add newone class to DIV
  const login = document.getElementById("login");
  
  login.classList.add("active");

  const registerTab = document.getElementById("registerTab");
  hide(registerTab)
  const loginTab = document.getElementById("loginTab");
  show(loginTab);

      //element.classList.remove("mystyle");
      //$('.login a').tab('show');
      //('.register a').hide(); 
}

function RegisterShow() {
  var url = document.getElementById("register").getAttribute("data-url");
  document.location.href = url
  const register = document.getElementById("register");  // Get the DIV element
  register.classList.add("active"); // Add newone class to DIV
  const login = document.getElementById("login");
  login.classList.remove("active");

  const registerTab = document.getElementById("registerTab");
  show(registerTab)
  const loginTab = document.getElementById("loginTab");
  hide(loginTab)
}


hide(registerTab)

  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  {% block jquery %}{% endblock %}
</html>

recipes/templates/recipe/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Recetas</title>
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    
    <div class="container">
      <div class="left-side">
        <img src="{% static 'img/cupcake.jpg' %}" alt="Cupcake">
      </div>
      <div class="right-side">
        <div class="text-center">
          <h1>RECETAS</h1>
        </div>
        <div class="tabs">
          <button id= "login" class="position-relative" onclick="loginShow()" data-url="{% url 'recipes:index' %}">Iniciar Sesión</button>
          <button id ="register" class="active position-relative" onclick="RegisterShow()" data-url="{% url 'recipes:register' %}">Registrarme</button>
        </div>
          <div id ="registerTab" class="position-relative">
          <form id="register-form" method="POST" autocomplete="off">
            <div class="mb-3">
            {{registerform.as_p}}
              {% csrf_token %}
              <button type="submit" class="btn btn-warning w-100 position-relative">Registrarse</button>
            </div>
        </form>
      </div>
        </div>
        
    </div>
  </body>
  <script>

function hide (elements) {
  elements = elements.length ? elements : [elements];
  for (var index = 0; index < elements.length; index++) {
    elements[index].style.display = 'none';
  }
}

function show (elements, specifiedDisplay) {
  elements = elements.length ? elements : [elements];
  for (var index = 0; index < elements.length; index++) {
    elements[index].style.display = specifiedDisplay || 'block';
  }
}

function loginShow() {
  var url = document.getElementById("login").getAttribute("data-url");
  document.location.href = url
  const register = document.getElementById("register");  // Get the DIV element
  register.classList.remove("active"); // Add newone class to DIV
  const login = document.getElementById("login");
  
  login.classList.add("active");

  const registerTab = document.getElementById("registerTab");
  hide(registerTab)
  const loginTab = document.getElementById("loginTab");
  show(loginTab);

      //element.classList.remove("mystyle");
      //$('.login a').tab('show');
      //('.register a').hide(); 
}

function RegisterShow() {
  var url = document.getElementById("register").getAttribute("data-url");
  document.location.href = url
  const register = document.getElementById("register");  // Get the DIV element
  register.classList.add("active"); // Add newone class to DIV
  const login = document.getElementById("login");
  login.classList.remove("active");

  const registerTab = document.getElementById("registerTab");
  show(registerTab)
  const loginTab = document.getElementById("loginTab");
  hide(loginTab)
}


hide(loginTab)

  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  {% block jquery %}{% endblock %}
</html>